name: CI/CD to EC2

on:
  push:
    branches: [ "QA" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      # 游댳 Construir la aplicaci칩n y generar el .jar
      - name: Build Java Application
        run: mvn clean package -DskipTests

      # 游댳 Verificar que el .jar se gener칩 correctamente
      - name: List files in target directory
        run: ls -l target/

      # 游댳 Login en Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # 游댳 Construir la imagen de Docker
      - name: Build Docker Image
        run: docker build -t anggeloo/microservice-update-inventory:latest .

      # 游댳 Subir la imagen a Docker Hub
      - name: Push Docker Image
        run: docker push anggeloo/microservice-update-inventory:latest

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Descargar la 칰ltima versi칩n de la imagen desde Docker Hub
            docker pull anggeloo/microservice-update-inventory:latest

            # 2) Detener y eliminar el contenedor previo si existe
            docker stop product_container || true
            docker rm product_container || true

            # 3) Crear un archivo .env con las credenciales necesarias
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            # Agrega m치s variables si es necesario

            # 4) Correr el nuevo contenedor con las variables de entorno
            docker run -d --name product_container \
              --env-file .env \
              -p 8082:8082 \
              anggeloo/microservice-update-inventory:latest
